version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "wp2024-lab"
    environment:
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=lab123
      - POSTGRES_DB=music
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/dataLab